#ifndef _H_i8086_TABLE
#define _H_i8086_TABLE

typedef enum { 
    Mneumonic_none,

    Mneumonic_add,
    Mneumonic_push,
    Mneumonic_pop,
    Mneumonic_or,
    Mneumonic_adc,
    Mneumonic_sbb,
    Mneumonic_and,
    Mneumonic_es,
    Mneumonic_daa,
    Mneumonic_sub,
    Mneumonic_cs,
    Mneumonic_das,
    Mneumonic_xor,
    Mneumonic_ss,
    Mneumonic_aaa,
    Mneumonic_cmp,
    Mneumonic_ds,
    Mneumonic_aas,
    Mneumonic_inc,
    Mneumonic_dec,
    Mneumonic_jo,
    Mneumonic_jno,
    Mneumonic_jb,
    Mneumonic_jnb,
    Mneumonic_jz,
    Mneumonic_jnz,
    Mneumonic_jbe,
    Mneumonic_ja,
    Mneumonic_js,
    Mneumonic_jns,
    Mneumonic_jpe,
    Mneumonic_jpo,
    Mneumonic_jl,
    Mneumonic_jge,
    Mneumonic_jle,
    Mneumonic_jg,
    Mneumonic_test,
    Mneumonic_xchg,
    Mneumonic_mov,
    Mneumonic_lea,
    Mneumonic_nop,
    Mneumonic_cbw,
    Mneumonic_cwd,
    Mneumonic_call,
    Mneumonic_wait,
    Mneumonic_pushf,
    Mneumonic_popf,
    Mneumonic_sahf,
    Mneumonic_lahf,
    Mneumonic_movsb,
    Mneumonic_movsw,
    Mneumonic_cmpsb,
    Mneumonic_cmpsw,
    Mneumonic_stosb,
    Mneumonic_stosw,
    Mneumonic_lodsb,
    Mneumonic_lodsw,
    Mneumonic_scasb,
    Mneumonic_scasw,
    Mneumonic_ret,
    Mneumonic_les,
    Mneumonic_lds,
    Mneumonic_retf,
    Mneumonic_int,
    Mneumonic_into,
    Mneumonic_iret,
    Mneumonic_aam,
    Mneumonic_aad,
    Mneumonic_xlat,
    Mneumonic_loopnz,
    Mneumonic_loopz,
    Mneumonic_loop,
    Mneumonic_jcxz,
    Mneumonic_in,
    Mneumonic_out,
    Mneumonic_jmp,
    Mneumonic_lock,
    Mneumonic_repnz,
    Mneumonic_repz,
    Mneumonic_hlt,
    Mneumonic_cmc,
    Mneumonic_clc,
    Mneumonic_stc,
    Mneumonic_cli,
    Mneumonic_sti,
    Mneumonic_cld,
    Mneumonic_std,

    Mneumonic_grp1,
    Mneumonic_grp2,
    Mneumonic_grp3a,
    Mneumonic_grp3b,
    Mneumonic_grp4,
    Mneumonic_grp5,

    Mneumonic_count,
} Mneumonic;

typedef struct i8086_Inst_Table i8086_Inst_Table;

struct i8086_Inst_Table {
    u8 opcode;
    Mneumonic mnemonic;
    const char* operands;
};

const i8086_Inst_Table i8086_inst_table[256] = {
    { 0x00, Mneumonic_add, "Eb", "Gb" },
    { 0x01, Mneumonic_add, "Ev", "Gv" },
    { 0x02, Mneumonic_add, "Gb", "Eb" },
    { 0x03, Mneumonic_add, "Gv", "Ev" },
    { 0x04, Mneumonic_add, "AL", "Ib" },
    { 0x05, Mneumonic_add, "eAX", "Iv" },
    { 0x06, Mneumonic_push, "ES", NULL },
    { 0x07, Mneumonic_pop, "ES", NULL },
    { 0x08, Mneumonic_or, "Eb", "Gb" },
    { 0x09, Mneumonic_or, "Ev", "Gv" },
    { 0x0A, Mneumonic_or, "Gb", "Eb" },
    { 0x0B, Mneumonic_or, "Gv", "Ev" },
    { 0x0C, Mneumonic_or, "AL", "Ib" },
    { 0x0D, Mneumonic_or, "eAX", "Iv" },
    { 0x0E, Mneumonic_push, "CS", NULL },
    { 0x0F, Mneumonic_none, NULL, NULL },
    { 0x10, Mneumonic_adc, "Eb", "Gb" },
    { 0x11, Mneumonic_adc, "Ev", "Gv" },
    { 0x12, Mneumonic_adc, "Gb", "Eb" },
    { 0x13, Mneumonic_adc, "Gv", "Ev" },
    { 0x14, Mneumonic_adc, "AL", "Ib" },
    { 0x15, Mneumonic_adc, "eAX", "Iv" },
    { 0x16, Mneumonic_push, "SS", NULL },
    { 0x17, Mneumonic_pop, "SS", NULL },
    { 0x18, Mneumonic_sbb, "Eb", "Gb" },
    { 0x19, Mneumonic_sbb, "Ev", "Gv" },
    { 0x1A, Mneumonic_sbb, "Gb", "Eb" },
    { 0x1B, Mneumonic_sbb, "Gv", "Ev" },
    { 0x1C, Mneumonic_sbb, "AL", "Ib" },
    { 0x1D, Mneumonic_sbb, "eAX", "Iv" },
    { 0x1E, Mneumonic_push, "DS", NULL },
    { 0x1F, Mneumonic_pop, "DS", NULL },
    { 0x20, Mneumonic_and, "Eb", "Gb" },
    { 0x21, Mneumonic_and, "Ev", "Gv" },
    { 0x22, Mneumonic_and, "Gb", "Eb" },
    { 0x23, Mneumonic_and, "Gv", "Ev" },
    { 0x24, Mneumonic_and, "AL", "Ib" },
    { 0x25, Mneumonic_and, "eAX", "Iv" },
    { 0x26, Mneumonic_es, NULL, NULL },
    { 0x27, Mneumonic_daa, NULL, NULL },
    { 0x28, Mneumonic_sub, "Eb", "Gb" },
    { 0x29, Mneumonic_sub, "Ev", "Gv" },
    { 0x2A, Mneumonic_sub, "Gb", "Eb" },
    { 0x2B, Mneumonic_sub, "Gv", "Ev" },
    { 0x2C, Mneumonic_sub, "AL", "Ib" },
    { 0x2D, Mneumonic_sub, "eAX", "Iv" },
    { 0x2E, Mneumonic_cs, NULL, NULL },
    { 0x2F, Mneumonic_das, NULL, NULL },
    { 0x30, Mneumonic_xor, "Eb", "Gb" },
    { 0x31, Mneumonic_xor, "Ev", "Gv" },
    { 0x32, Mneumonic_xor, "Gb", "Eb" },
    { 0x33, Mneumonic_xor, "Gv", "Ev" },
    { 0x34, Mneumonic_xor, "AL", "Ib" },
    { 0x35, Mneumonic_xor, "eAX", "Iv" },
    { 0x36, Mneumonic_ss, NULL, NULL },
    { 0x37, Mneumonic_aaa, NULL, NULL },
    { 0x38, Mneumonic_cmp, "Eb", "Gb" },
    { 0x39, Mneumonic_cmp, "Ev", "Gv" },
    { 0x3A, Mneumonic_cmp, "Gb", "Eb" },
    { 0x3B, Mneumonic_cmp, "Gv", "Ev" },
    { 0x3C, Mneumonic_cmp, "AL", "Ib" },
    { 0x3D, Mneumonic_cmp, "eAX", "Iv" },
    { 0x3E, Mneumonic_ds, NULL, NULL },
    { 0x3F, Mneumonic_aas, NULL, NULL },
    { 0x40, Mneumonic_inc, "eAX", NULL },
    { 0x41, Mneumonic_inc, "eCX", NULL },
    { 0x42, Mneumonic_inc, "eDX", NULL },
    { 0x43, Mneumonic_inc, "eBX", NULL },
    { 0x44, Mneumonic_inc, "eSP", NULL },
    { 0x45, Mneumonic_inc, "eBP", NULL },
    { 0x46, Mneumonic_inc, "eSI", NULL },
    { 0x47, Mneumonic_inc, "eDI", NULL },
    { 0x48, Mneumonic_dec, "eAX", NULL },
    { 0x49, Mneumonic_dec, "eCX", NULL },
    { 0x4A, Mneumonic_dec, "eDX", NULL },
    { 0x4B, Mneumonic_dec, "eBX", NULL },
    { 0x4C, Mneumonic_dec, "eSP", NULL },
    { 0x4D, Mneumonic_dec, "eBP", NULL },
    { 0x4E, Mneumonic_dec, "eSI", NULL },
    { 0x4F, Mneumonic_dec, "eDI", NULL },
    { 0x50, Mneumonic_push, "eAX", NULL },
    { 0x51, Mneumonic_push, "eCX", NULL },
    { 0x52, Mneumonic_push, "eDX", NULL },
    { 0x53, Mneumonic_push, "eBX", NULL },
    { 0x54, Mneumonic_push, "eSP", NULL },
    { 0x55, Mneumonic_push, "eBP", NULL },
    { 0x56, Mneumonic_push, "eSI", NULL },
    { 0x57, Mneumonic_push, "eDI", NULL },
    { 0x58, Mneumonic_pop, "eAX", NULL },
    { 0x59, Mneumonic_pop, "eCX", NULL },
    { 0x5A, Mneumonic_pop, "eDX", NULL },
    { 0x5B, Mneumonic_pop, "eBX", NULL },
    { 0x5C, Mneumonic_pop, "eSP", NULL },
    { 0x5D, Mneumonic_pop, "eBP", NULL },
    { 0x5E, Mneumonic_pop, "eSI", NULL },
    { 0x5F, Mneumonic_pop, "eDI", NULL },
    { 0x60, Mneumonic_none, NULL, NULL },
    { 0x61, Mneumonic_none, NULL, NULL },
    { 0x62, Mneumonic_none, NULL, NULL },
    { 0x63, Mneumonic_none, NULL, NULL },
    { 0x64, Mneumonic_none, NULL, NULL },
    { 0x65, Mneumonic_none, NULL, NULL },
    { 0x66, Mneumonic_none, NULL, NULL },
    { 0x67, Mneumonic_none, NULL, NULL },
    { 0x68, Mneumonic_none, NULL, NULL },
    { 0x69, Mneumonic_none, NULL, NULL },
    { 0x6A, Mneumonic_none, NULL, NULL },
    { 0x6B, Mneumonic_none, NULL, NULL },
    { 0x6C, Mneumonic_none, NULL, NULL },
    { 0x6D, Mneumonic_none, NULL, NULL },
    { 0x6E, Mneumonic_none, NULL, NULL },
    { 0x6F, Mneumonic_none, NULL, NULL },
    { 0x70, Mneumonic_jo, "Jb", NULL },
    { 0x71, Mneumonic_jno, "Jb", NULL },
    { 0x72, Mneumonic_jb, "Jb", NULL },
    { 0x73, Mneumonic_jnb, "Jb", NULL },
    { 0x74, Mneumonic_jz, "Jb", NULL },
    { 0x75, Mneumonic_jnz, "Jb", NULL },
    { 0x76, Mneumonic_jbe, "Jb", NULL },
    { 0x77, Mneumonic_ja, "Jb", NULL },
    { 0x78, Mneumonic_js, "Jb", NULL },
    { 0x79, Mneumonic_jns, "Jb", NULL },
    { 0x7A, Mneumonic_jpe, "Jb", NULL },
    { 0x7B, Mneumonic_jpo, "Jb", NULL },
    { 0x7C, Mneumonic_jl, "Jb", NULL },
    { 0x7D, Mneumonic_jge, "Jb", NULL },
    { 0x7E, Mneumonic_jle, "Jb", NULL },
    { 0x7F, Mneumonic_jg, "Jb", NULL },
    { 0x80, Mneumonic_grp1, "Eb", "Ib" },
    { 0x81, Mneumonic_grp1, "Ev", "Iv" },
    { 0x82, Mneumonic_grp1, "Eb", "Ib" },
    { 0x83, Mneumonic_grp1, "Ev", "Ib" },
    { 0x84, Mneumonic_test, "Gb", "Eb" },
    { 0x85, Mneumonic_test, "Gv", "Ev" },
    { 0x86, Mneumonic_xchg, "Gb", "Eb" },
    { 0x87, Mneumonic_xchg, "Gv", "Ev" },
    { 0x88, Mneumonic_mov, "Eb", "Gb" },
    { 0x89, Mneumonic_mov, "Ev", "Gv" },
    { 0x8A, Mneumonic_mov, "Gb", "Eb" },
    { 0x8B, Mneumonic_mov, "Gv", "Ev" },
    { 0x8C, Mneumonic_mov, "Ew", "Sw" },
    { 0x8D, Mneumonic_lea, "Gv", "M" },
    { 0x8E, Mneumonic_mov, "Sw", "Ew" },
    { 0x8F, Mneumonic_pop, "Ev", NULL },
    { 0x90, Mneumonic_nop, NULL, NULL },
    { 0x91, Mneumonic_xchg, "eCX", "eAX" },
    { 0x92, Mneumonic_xchg, "eDX", "eAX" },
    { 0x93, Mneumonic_xchg, "eBX", "eAX" },
    { 0x94, Mneumonic_xchg, "eSP", "eAX" },
    { 0x95, Mneumonic_xchg, "eBP", "eAX" },
    { 0x96, Mneumonic_xchg, "eSI", "eAX" },
    { 0x97, Mneumonic_xchg, "eDI", "eAX" },
    { 0x98, Mneumonic_cbw, NULL, NULL },
    { 0x99, Mneumonic_cwd, NULL, NULL },
    { 0x9A, Mneumonic_call, "Ap", NULL },
    { 0x9B, Mneumonic_wait, NULL, NULL },
    { 0x9C, Mneumonic_pushf, NULL, NULL },
    { 0x9D, Mneumonic_popf, NULL, NULL },
    { 0x9E, Mneumonic_sahf, NULL, NULL },
    { 0x9F, Mneumonic_lahf, NULL, NULL },
    { 0xA0, Mneumonic_mov, "AL", "Ob" },
    { 0xA1, Mneumonic_mov, "eAX", "Ov" },
    { 0xA2, Mneumonic_mov, "Ob", "AL" },
    { 0xA3, Mneumonic_mov, "Ov", "eAX" },
    { 0xA4, Mneumonic_movsb, NULL, NULL },
    { 0xA5, Mneumonic_movsw, NULL, NULL },
    { 0xA6, Mneumonic_cmpsb, NULL, NULL },
    { 0xA7, Mneumonic_cmpsw, NULL, NULL },
    { 0xA8, Mneumonic_test, "AL", "Ib" },
    { 0xA9, Mneumonic_test, "eAX", "Iv" },
    { 0xAA, Mneumonic_stosb, NULL, NULL },
    { 0xAB, Mneumonic_stosw, NULL, NULL },
    { 0xAC, Mneumonic_lodsb, NULL, NULL },
    { 0xAD, Mneumonic_lodsw, NULL, NULL },
    { 0xAE, Mneumonic_scasb, NULL, NULL },
    { 0xAF, Mneumonic_scasw, NULL, NULL },
    { 0xB0, Mneumonic_mov, "AL", "Ib" },
    { 0xB1, Mneumonic_mov, "CL", "Ib" },
    { 0xB2, Mneumonic_mov, "DL", "Ib" },
    { 0xB3, Mneumonic_mov, "BL", "Ib" },
    { 0xB4, Mneumonic_mov, "AH", "Ib" },
    { 0xB5, Mneumonic_mov, "CH", "Ib" },
    { 0xB6, Mneumonic_mov, "DH", "Ib" },
    { 0xB7, Mneumonic_mov, "BH", "Ib" },
    { 0xB8, Mneumonic_mov, "eAX", "Iv" },
    { 0xB9, Mneumonic_mov, "eCX", "Iv" },
    { 0xBA, Mneumonic_mov, "eDX", "Iv" },
    { 0xBB, Mneumonic_mov, "eBX", "Iv" },
    { 0xBC, Mneumonic_mov, "eSP", "Iv" },
    { 0xBD, Mneumonic_mov, "eBP", "Iv" },
    { 0xBE, Mneumonic_mov, "eSI", "Iv" },
    { 0xBF, Mneumonic_mov, "eDI", "Iv" },
    { 0xC0, Mneumonic_none, NULL, NULL },
    { 0xC1, Mneumonic_none, NULL, NULL },
    { 0xC2, Mneumonic_ret, "Iw", NULL },
    { 0xC3, Mneumonic_ret, NULL, NULL },
    { 0xC4, Mneumonic_les, "Gv", "Mp" },
    { 0xC5, Mneumonic_lds, "Gv", "Mp" },
    { 0xC6, Mneumonic_mov, "Eb", "Ib" },
    { 0xC7, Mneumonic_mov, "Ev", "Iv" },
    { 0xC8, Mneumonic_none, NULL, NULL },
    { 0xC9, Mneumonic_none, NULL, NULL },
    { 0xCA, Mneumonic_retf, "Iw", NULL },
    { 0xCB, Mneumonic_retf, NULL, NULL },
    { 0xCC, Mneumonic_int, "3", NULL },
    { 0xCD, Mneumonic_int, "Ib", NULL },
    { 0xCE, Mneumonic_into, NULL, NULL },
    { 0xCF, Mneumonic_iret, NULL, NULL },
    { 0xD0, Mneumonic_grp2, "Eb", "1" },
    { 0xD1, Mneumonic_grp2, "Ev", "1" },
    { 0xD2, Mneumonic_grp2, "Eb", "CL" },
    { 0xD3, Mneumonic_grp2, "Ev", "CL" },
    { 0xD4, Mneumonic_aam, "I0", NULL },
    { 0xD5, Mneumonic_aad, "I0", NULL },
    { 0xD6, Mneumonic_none, NULL, NULL },
    { 0xD7, Mneumonic_xlat, NULL, NULL },
    { 0xD8, Mneumonic_none, NULL, NULL },
    { 0xD9, Mneumonic_none, NULL, NULL },
    { 0xDA, Mneumonic_none, NULL, NULL },
    { 0xDB, Mneumonic_none, NULL, NULL },
    { 0xDC, Mneumonic_none, NULL, NULL },
    { 0xDD, Mneumonic_none, NULL, NULL },
    { 0xDE, Mneumonic_none, NULL, NULL },
    { 0xDF, Mneumonic_none, NULL, NULL },
    { 0xE0, Mneumonic_loopnz, "Jb", NULL },
    { 0xE1, Mneumonic_loopz, "Jb", NULL },
    { 0xE2, Mneumonic_loop, "Jb", NULL },
    { 0xE3, Mneumonic_jcxz, "Jb", NULL },
    { 0xE4, Mneumonic_in, "AL", "Ib" },
    { 0xE5, Mneumonic_in, "eAX", "Ib" },
    { 0xE6, Mneumonic_out, "Ib", "AL" },
    { 0xE7, Mneumonic_out, "Ib", "eAX" },
    { 0xE8, Mneumonic_call, "Jv", NULL },
    { 0xE9, Mneumonic_jmp, "Jv", NULL },
    { 0xEA, Mneumonic_jmp, "Ap", NULL },
    { 0xEB, Mneumonic_jmp, "Jb", NULL },
    { 0xEC, Mneumonic_in, "AL", "DX" },
    { 0xED, Mneumonic_in, "eAX", "DX" },
    { 0xEE, Mneumonic_out, "DX", "AL" },
    { 0xEF, Mneumonic_out, "DX", "eAX" },
    { 0xF0, Mneumonic_lock, NULL, NULL },
    { 0xF1, Mneumonic_none, NULL, NULL },
    { 0xF2, Mneumonic_repnz, NULL, NULL },
    { 0xF3, Mneumonic_repz, NULL, NULL },
    { 0xF4, Mneumonic_hlt, NULL, NULL },
    { 0xF5, Mneumonic_cmc, NULL, NULL },
    { 0xF6, Mneumonic_grp3a, "Eb", NULL },
    { 0xF7, Mneumonic_grp3b, "Ev", NULL },
    { 0xF8, Mneumonic_clc, NULL, NULL },
    { 0xF9, Mneumonic_stc, NULL, NULL },
    { 0xFA, Mneumonic_cli, NULL, NULL },
    { 0xFB, Mneumonic_sti, NULL, NULL },
    { 0xFC, Mneumonic_cld, NULL, NULL },
    { 0xFD, Mneumonic_std, NULL, NULL },
    { 0xFE, Mneumonic_grp4, "Eb", NULL },
    { 0xFF, Mneumonic_grp5, "Ev", NULL },
};


#endif