#ifndef _H_i8086_TABLE
#define _H_i8086_TABLE 1

#include "sim86.h"

typedef enum {
    Mnemonic_none,

    Mnemonic_add,
    Mnemonic_push,
    Mnemonic_pop,
    Mnemonic_or,
    Mnemonic_adc,
    Mnemonic_sbb,
    Mnemonic_and,
    Mnemonic_es,
    Mnemonic_daa,
    Mnemonic_sub,
    Mnemonic_cs,
    Mnemonic_das,
    Mnemonic_xor,
    Mnemonic_ss,
    Mnemonic_aaa,
    Mnemonic_cmp,
    Mnemonic_ds,
    Mnemonic_aas,
    Mnemonic_inc,
    Mnemonic_dec,
    Mnemonic_jo,
    Mnemonic_jno,
    Mnemonic_jb,
    Mnemonic_jnb,
    Mnemonic_jz,
    Mnemonic_jnz,
    Mnemonic_jbe,
    Mnemonic_ja,
    Mnemonic_js,
    Mnemonic_jns,
    Mnemonic_jp,
    Mnemonic_jnp,
    Mnemonic_jl,
    Mnemonic_jnl,
    Mnemonic_jle,
    Mnemonic_jg,
    Mnemonic_test,
    Mnemonic_xchg,
    Mnemonic_mov,
    Mnemonic_lea,
    Mnemonic_nop,
    Mnemonic_cbw,
    Mnemonic_cwd,
    Mnemonic_call,
    Mnemonic_wait,
    Mnemonic_pushf,
    Mnemonic_popf,
    Mnemonic_sahf,
    Mnemonic_lahf,
    Mnemonic_movsb,
    Mnemonic_movsw,
    Mnemonic_cmpsb,
    Mnemonic_cmpsw,
    Mnemonic_stosb,
    Mnemonic_stosw,
    Mnemonic_lodsb,
    Mnemonic_lodsw,
    Mnemonic_scasb,
    Mnemonic_scasw,
    Mnemonic_ret,
    Mnemonic_les,
    Mnemonic_lds,
    Mnemonic_retf,
    Mnemonic_int,
    Mnemonic_into,
    Mnemonic_iret,
    Mnemonic_aam,
    Mnemonic_aad,
    Mnemonic_xlat,
    Mnemonic_loopnz,
    Mnemonic_loopz,
    Mnemonic_loop,
    Mnemonic_jcxz,
    Mnemonic_in,
    Mnemonic_out,
    Mnemonic_jmp,
    Mnemonic_lock,
    Mnemonic_repnz,
    Mnemonic_repz,
    Mnemonic_hlt,
    Mnemonic_cmc,
    Mnemonic_clc,
    Mnemonic_stc,
    Mnemonic_cli,
    Mnemonic_sti,
    Mnemonic_cld,
    Mnemonic_std,

    Mnemonic_rol,
    Mnemonic_ror,
    Mnemonic_rcl,
    Mnemonic_rcr,
    Mnemonic_shl,
    Mnemonic_shr,
    Mnemonic_sar,
    Mnemonic_not,
    Mnemonic_neg,
    Mnemonic_mul,
    Mnemonic_imul,
    Mnemonic_div,
    Mnemonic_idiv,

    Mnemonic_db,

    Mnemonic_grp1,
    Mnemonic_grp2,
    Mnemonic_grp3a,
    Mnemonic_grp3b,
    Mnemonic_grp4,
    Mnemonic_grp5,

    Mnemonic_invalid,

    Mnemonic_count,
} Mnemonic;

typedef struct i8086_Inst_Table i8086_Inst_Table;

struct i8086_Inst_Table {
    u8 opcode;
    Mnemonic mnemonic;
    const char* arg1;
    const char* arg2;
    Instruction_Type type;
};

/*
  Instruction_Type_move
  Instruction_Type_arithmetic,
  Instruction_Type_flow,
  Instruction_Type_stack,
*/

static const i8086_Inst_Table i8086_inst_table[] = {
    { 0x00, Mnemonic_add, "Eb", "Gb", Instruction_Type_arithmetic },
    { 0x01, Mnemonic_add, "Ev", "Gv", Instruction_Type_arithmetic },
    { 0x02, Mnemonic_add, "Gb", "Eb", Instruction_Type_arithmetic },
    { 0x03, Mnemonic_add, "Gv", "Ev", Instruction_Type_arithmetic },
    { 0x04, Mnemonic_add, "AL", "Ib", Instruction_Type_arithmetic },
    { 0x05, Mnemonic_add, "eAX", "Iv", Instruction_Type_arithmetic },
    { 0x06, Mnemonic_push, "ES", NULL, Instruction_Type_stack },
    { 0x07, Mnemonic_pop, "ES", NULL, Instruction_Type_stack },
    { 0x08, Mnemonic_or, "Eb", "Gb" },
    { 0x09, Mnemonic_or, "Ev", "Gv" },
    { 0x0A, Mnemonic_or, "Gb", "Eb" },
    { 0x0B, Mnemonic_or, "Gv", "Ev" },
    { 0x0C, Mnemonic_or, "AL", "Ib" },
    { 0x0D, Mnemonic_or, "eAX", "Iv" },
    { 0x0E, Mnemonic_push, "CS", NULL, Instruction_Type_stack },
    { 0x0F, Mnemonic_db, NULL, NULL },
    { 0x10, Mnemonic_adc, "Eb", "Gb" },
    { 0x11, Mnemonic_adc, "Ev", "Gv" },
    { 0x12, Mnemonic_adc, "Gb", "Eb" },
    { 0x13, Mnemonic_adc, "Gv", "Ev" },
    { 0x14, Mnemonic_adc, "AL", "Ib" },
    { 0x15, Mnemonic_adc, "eAX", "Iv" },
    { 0x16, Mnemonic_push, "SS", NULL, Instruction_Type_stack },
    { 0x17, Mnemonic_pop, "SS", NULL, Instruction_Type_stack },
    { 0x18, Mnemonic_sbb, "Eb", "Gb" },
    { 0x19, Mnemonic_sbb, "Ev", "Gv" },
    { 0x1A, Mnemonic_sbb, "Gb", "Eb" },
    { 0x1B, Mnemonic_sbb, "Gv", "Ev" },
    { 0x1C, Mnemonic_sbb, "AL", "Ib" },
    { 0x1D, Mnemonic_sbb, "eAX", "Iv" },
    { 0x1E, Mnemonic_push, "DS", NULL, Instruction_Type_stack },
    { 0x1F, Mnemonic_pop, "DS", NULL, Instruction_Type_stack },
    { 0x20, Mnemonic_and, "Eb", "Gb" },
    { 0x21, Mnemonic_and, "Ev", "Gv" },
    { 0x22, Mnemonic_and, "Gb", "Eb" },
    { 0x23, Mnemonic_and, "Gv", "Ev" },
    { 0x24, Mnemonic_and, "AL", "Ib" },
    { 0x25, Mnemonic_and, "eAX", "Iv" },
    { 0x26, Mnemonic_es, NULL, NULL },
    { 0x27, Mnemonic_daa, NULL, NULL },
    { 0x28, Mnemonic_sub, "Eb", "Gb" },
    { 0x29, Mnemonic_sub, "Ev", "Gv" },
    { 0x2A, Mnemonic_sub, "Gb", "Eb" },
    { 0x2B, Mnemonic_sub, "Gv", "Ev" },
    { 0x2C, Mnemonic_sub, "AL", "Ib" },
    { 0x2D, Mnemonic_sub, "eAX", "Iv" },
    { 0x2E, Mnemonic_cs, NULL, NULL },
    { 0x2F, Mnemonic_das, NULL, NULL },
    { 0x30, Mnemonic_xor, "Eb", "Gb", Instruction_Type_logical },
    { 0x31, Mnemonic_xor, "Ev", "Gv", Instruction_Type_logical },
    { 0x32, Mnemonic_xor, "Gb", "Eb", Instruction_Type_logical },
    { 0x33, Mnemonic_xor, "Gv", "Ev", Instruction_Type_logical },
    { 0x34, Mnemonic_xor, "AL", "Ib", Instruction_Type_logical },
    { 0x35, Mnemonic_xor, "eAX", "Iv", Instruction_Type_logical },
    { 0x36, Mnemonic_ss, NULL, NULL },
    { 0x37, Mnemonic_aaa, NULL, NULL },
    { 0x38, Mnemonic_cmp, "Eb", "Gb", Instruction_Type_arithmetic },
    { 0x39, Mnemonic_cmp, "Ev", "Gv", Instruction_Type_arithmetic },
    { 0x3A, Mnemonic_cmp, "Gb", "Eb", Instruction_Type_arithmetic },
    { 0x3B, Mnemonic_cmp, "Gv", "Ev", Instruction_Type_arithmetic },
    { 0x3C, Mnemonic_cmp, "AL", "Ib", Instruction_Type_arithmetic },
    { 0x3D, Mnemonic_cmp, "eAX", "Iv", Instruction_Type_arithmetic },
    { 0x3E, Mnemonic_ds, NULL, NULL },
    { 0x3F, Mnemonic_aas, NULL, NULL },
    { 0x40, Mnemonic_inc, "eAX", NULL },
    { 0x41, Mnemonic_inc, "eCX", NULL },
    { 0x42, Mnemonic_inc, "eDX", NULL },
    { 0x43, Mnemonic_inc, "eBX", NULL },
    { 0x44, Mnemonic_inc, "eSP", NULL },
    { 0x45, Mnemonic_inc, "eBP", NULL },
    { 0x46, Mnemonic_inc, "eSI", NULL },
    { 0x47, Mnemonic_inc, "eDI", NULL },
    { 0x48, Mnemonic_dec, "eAX", NULL },
    { 0x49, Mnemonic_dec, "eCX", NULL },
    { 0x4A, Mnemonic_dec, "eDX", NULL },
    { 0x4B, Mnemonic_dec, "eBX", NULL },
    { 0x4C, Mnemonic_dec, "eSP", NULL },
    { 0x4D, Mnemonic_dec, "eBP", NULL },
    { 0x4E, Mnemonic_dec, "eSI", NULL },
    { 0x4F, Mnemonic_dec, "eDI", NULL },
    { 0x50, Mnemonic_push, "eAX", NULL, Instruction_Type_stack },
    { 0x51, Mnemonic_push, "eCX", NULL, Instruction_Type_stack },
    { 0x52, Mnemonic_push, "eDX", NULL, Instruction_Type_stack },
    { 0x53, Mnemonic_push, "eBX", NULL, Instruction_Type_stack },
    { 0x54, Mnemonic_push, "eSP", NULL, Instruction_Type_stack },
    { 0x55, Mnemonic_push, "eBP", NULL, Instruction_Type_stack },
    { 0x56, Mnemonic_push, "eSI", NULL, Instruction_Type_stack },
    { 0x57, Mnemonic_push, "eDI", NULL, Instruction_Type_stack },
    { 0x58, Mnemonic_pop, "eAX", NULL, Instruction_Type_stack },
    { 0x59, Mnemonic_pop, "eCX", NULL, Instruction_Type_stack },
    { 0x5A, Mnemonic_pop, "eDX", NULL, Instruction_Type_stack },
    { 0x5B, Mnemonic_pop, "eBX", NULL, Instruction_Type_stack },
    { 0x5C, Mnemonic_pop, "eSP", NULL, Instruction_Type_stack },
    { 0x5D, Mnemonic_pop, "eBP", NULL, Instruction_Type_stack },
    { 0x5E, Mnemonic_pop, "eSI", NULL, Instruction_Type_stack },
    { 0x5F, Mnemonic_pop, "eDI", NULL, Instruction_Type_stack },
    { 0x60, Mnemonic_db, NULL, NULL },
    { 0x61, Mnemonic_db, NULL, NULL },
    { 0x62, Mnemonic_db, NULL, NULL },
    { 0x63, Mnemonic_db, NULL, NULL },
    { 0x64, Mnemonic_db, NULL, NULL },
    { 0x65, Mnemonic_db, NULL, NULL },
    { 0x66, Mnemonic_db, NULL, NULL },
    { 0x67, Mnemonic_db, NULL, NULL },
    { 0x68, Mnemonic_db, NULL, NULL },
    { 0x69, Mnemonic_db, NULL, NULL },
    { 0x6A, Mnemonic_db, NULL, NULL },
    { 0x6B, Mnemonic_db, NULL, NULL },
    { 0x6C, Mnemonic_db, NULL, NULL },
    { 0x6D, Mnemonic_db, NULL, NULL },
    { 0x6E, Mnemonic_db, NULL, NULL },
    { 0x6F, Mnemonic_db, NULL, NULL },
    { 0x70, Mnemonic_jo, "Jb", NULL, Instruction_Type_flow },
    { 0x71, Mnemonic_jno, "Jb", NULL, Instruction_Type_flow },
    { 0x72, Mnemonic_jb, "Jb", NULL, Instruction_Type_flow },
    { 0x73, Mnemonic_jnb, "Jb", NULL, Instruction_Type_flow },
    { 0x74, Mnemonic_jz, "Jb", NULL, Instruction_Type_flow },
    { 0x75, Mnemonic_jnz, "Jb", NULL, Instruction_Type_flow },
    { 0x76, Mnemonic_jbe, "Jb", NULL, Instruction_Type_flow },
    { 0x77, Mnemonic_ja, "Jb", NULL, Instruction_Type_flow },
    { 0x78, Mnemonic_js, "Jb", NULL, Instruction_Type_flow },
    { 0x79, Mnemonic_jns, "Jb", NULL, Instruction_Type_flow },
    { 0x7A, Mnemonic_jp, "Jb", NULL, Instruction_Type_flow },
    { 0x7B, Mnemonic_jnp, "Jb", NULL, Instruction_Type_flow },
    { 0x7C, Mnemonic_jl, "Jb", NULL, Instruction_Type_flow },
    { 0x7D, Mnemonic_jnl, "Jb", NULL, Instruction_Type_flow },
    { 0x7E, Mnemonic_jle, "Jb", NULL, Instruction_Type_flow },
    { 0x7F, Mnemonic_jg, "Jb", NULL, Instruction_Type_flow },
    { 0x80, Mnemonic_grp1, "Eb", "Ib" },
    { 0x81, Mnemonic_grp1, "Ev", "Iv" },
    { 0x82, Mnemonic_grp1, "Eb", "Ib" },
    { 0x83, Mnemonic_grp1, "Ev", "Ib" },
    { 0x84, Mnemonic_test, "Gb", "Eb" },
    { 0x85, Mnemonic_test, "Gv", "Ev" },
    { 0x86, Mnemonic_xchg, "Gb", "Eb" },
    { 0x87, Mnemonic_xchg, "Gv", "Ev" },
    { 0x88, Mnemonic_mov, "Eb", "Gb", Instruction_Type_move },
    { 0x89, Mnemonic_mov, "Ev", "Gv", Instruction_Type_move },
    { 0x8A, Mnemonic_mov, "Gb", "Eb", Instruction_Type_move },
    { 0x8B, Mnemonic_mov, "Gv", "Ev", Instruction_Type_move },
    { 0x8C, Mnemonic_mov, "Ew", "Sw", Instruction_Type_move },
    { 0x8D, Mnemonic_lea, "Gv", "M" },
    { 0x8E, Mnemonic_mov, "Sw", "Ew", Instruction_Type_move },
    { 0x8F, Mnemonic_pop, "Ev", NULL, Instruction_Type_stack },
    { 0x90, Mnemonic_nop, NULL, NULL },
    { 0x91, Mnemonic_xchg, "eCX", "eAX" },
    { 0x92, Mnemonic_xchg, "eDX", "eAX" },
    { 0x93, Mnemonic_xchg, "eBX", "eAX" },
    { 0x94, Mnemonic_xchg, "eSP", "eAX" },
    { 0x95, Mnemonic_xchg, "eBP", "eAX" },
    { 0x96, Mnemonic_xchg, "eSI", "eAX" },
    { 0x97, Mnemonic_xchg, "eDI", "eAX" },
    { 0x98, Mnemonic_cbw, NULL, NULL },
    { 0x99, Mnemonic_cwd, NULL, NULL },
    { 0x9A, Mnemonic_call, "Ap", NULL },
    { 0x9B, Mnemonic_wait, NULL, NULL },
    { 0x9C, Mnemonic_pushf, NULL, NULL, Instruction_Type_stack },
    { 0x9D, Mnemonic_popf, NULL, NULL, Instruction_Type_stack },
    { 0x9E, Mnemonic_sahf, NULL, NULL },
    { 0x9F, Mnemonic_lahf, NULL, NULL },
    { 0xA0, Mnemonic_mov, "AL", "Ob",  Instruction_Type_move },
    { 0xA1, Mnemonic_mov, "eAX", "Ov", Instruction_Type_move },
    { 0xA2, Mnemonic_mov, "Ob", "AL",  Instruction_Type_move },
    { 0xA3, Mnemonic_mov, "Ov", "eAX", Instruction_Type_move },
    { 0xA4, Mnemonic_movsb, NULL, NULL, Instruction_Type_move },
    { 0xA5, Mnemonic_movsw, NULL, NULL, Instruction_Type_move },
    { 0xA6, Mnemonic_cmpsb, NULL, NULL, Instruction_Type_arithmetic },
    { 0xA7, Mnemonic_cmpsw, NULL, NULL, Instruction_Type_arithmetic },
    { 0xA8, Mnemonic_test, "AL", "Ib" },
    { 0xA9, Mnemonic_test, "eAX", "Iv" },
    { 0xAA, Mnemonic_stosb, NULL, NULL, Instruction_Type_string },
    { 0xAB, Mnemonic_stosw, NULL, NULL, Instruction_Type_string },
    { 0xAC, Mnemonic_lodsb, NULL, NULL },
    { 0xAD, Mnemonic_lodsw, NULL, NULL },
    { 0xAE, Mnemonic_scasb, NULL, NULL },
    { 0xAF, Mnemonic_scasw, NULL, NULL },
    { 0xB0, Mnemonic_mov, "AL", "Ib", Instruction_Type_move },
    { 0xB1, Mnemonic_mov, "CL", "Ib", Instruction_Type_move },
    { 0xB2, Mnemonic_mov, "DL", "Ib", Instruction_Type_move },
    { 0xB3, Mnemonic_mov, "BL", "Ib", Instruction_Type_move },
    { 0xB4, Mnemonic_mov, "AH", "Ib", Instruction_Type_move },
    { 0xB5, Mnemonic_mov, "CH", "Ib", Instruction_Type_move },
    { 0xB6, Mnemonic_mov, "DH", "Ib", Instruction_Type_move },
    { 0xB7, Mnemonic_mov, "BH", "Ib", Instruction_Type_move },
    { 0xB8, Mnemonic_mov, "eAX", "Iv", Instruction_Type_move },
    { 0xB9, Mnemonic_mov, "eCX", "Iv", Instruction_Type_move },
    { 0xBA, Mnemonic_mov, "eDX", "Iv", Instruction_Type_move },
    { 0xBB, Mnemonic_mov, "eBX", "Iv", Instruction_Type_move },
    { 0xBC, Mnemonic_mov, "eSP", "Iv", Instruction_Type_move },
    { 0xBD, Mnemonic_mov, "eBP", "Iv", Instruction_Type_move },
    { 0xBE, Mnemonic_mov, "eSI", "Iv", Instruction_Type_move },
    { 0xBF, Mnemonic_mov, "eDI", "Iv", Instruction_Type_move },
    { 0xC0, Mnemonic_db, NULL, NULL },
    { 0xC1, Mnemonic_db, NULL, NULL },
    { 0xC2, Mnemonic_ret, "Iw", NULL },
    { 0xC3, Mnemonic_ret, NULL, NULL },
    { 0xC4, Mnemonic_les, "Gv", "Mp" },
    { 0xC5, Mnemonic_lds, "Gv", "Mp" },
    { 0xC6, Mnemonic_mov, "Eb", "Ib", Instruction_Type_move },
    { 0xC7, Mnemonic_mov, "Ev", "Iv", Instruction_Type_move },
    { 0xC8, Mnemonic_db, NULL, NULL },
    { 0xC9, Mnemonic_db, NULL, NULL },
    { 0xCA, Mnemonic_retf, "Iw", NULL },
    { 0xCB, Mnemonic_retf, NULL, NULL },
    { 0xCC, Mnemonic_int, "3", NULL },
    { 0xCD, Mnemonic_int, "Ib", NULL },
    { 0xCE, Mnemonic_into, NULL, NULL },
    { 0xCF, Mnemonic_iret, NULL, NULL },
    { 0xD0, Mnemonic_grp2, "Eb", "1" },
    { 0xD1, Mnemonic_grp2, "Ev", "1" },
    { 0xD2, Mnemonic_grp2, "Eb", "CL" },
    { 0xD3, Mnemonic_grp2, "Ev", "CL" },
    { 0xD4, Mnemonic_aam, "I0", NULL },
    { 0xD5, Mnemonic_aad, "I0", NULL },
    { 0xD6, Mnemonic_db, NULL, NULL },
    { 0xD7, Mnemonic_xlat, NULL, NULL },
    { 0xD8, Mnemonic_db, NULL, NULL },
    { 0xD9, Mnemonic_db, NULL, NULL },
    { 0xDA, Mnemonic_db, NULL, NULL },
    { 0xDB, Mnemonic_db, NULL, NULL },
    { 0xDC, Mnemonic_db, NULL, NULL },
    { 0xDD, Mnemonic_db, NULL, NULL },
    { 0xDE, Mnemonic_db, NULL, NULL },
    { 0xDF, Mnemonic_db, NULL, NULL },
    { 0xE0, Mnemonic_loopnz, "Jb", NULL, Instruction_Type_flow },
    { 0xE1, Mnemonic_loopz, "Jb", NULL, Instruction_Type_flow },
    { 0xE2, Mnemonic_loop, "Jb", NULL, Instruction_Type_flow },
    { 0xE3, Mnemonic_jcxz, "Jb", NULL, Instruction_Type_flow },
    { 0xE4, Mnemonic_in, "AL", "Ib" },
    { 0xE5, Mnemonic_in, "eAX", "Ib" },
    { 0xE6, Mnemonic_out, "Ib", "AL", Instruction_Type_io },
    { 0xE7, Mnemonic_out, "Ib", "eAX", Instruction_Type_io },
    { 0xE8, Mnemonic_call, "Jv", NULL },
    { 0xE9, Mnemonic_jmp, "Jv", NULL, Instruction_Type_flow },
    { 0xEA, Mnemonic_jmp, "Ap", NULL, Instruction_Type_flow },
    { 0xEB, Mnemonic_jmp, "Jb", NULL, Instruction_Type_flow },
    { 0xEC, Mnemonic_in, "AL", "DX" },
    { 0xED, Mnemonic_in, "eAX", "DX" },
    { 0xEE, Mnemonic_out, "DX", "AL", Instruction_Type_io },
    { 0xEF, Mnemonic_out, "DX", "eAX", Instruction_Type_io },
    { 0xF0, Mnemonic_lock, NULL, NULL },
    { 0xF1, Mnemonic_db, NULL, NULL },
    { 0xF2, Mnemonic_repnz, NULL, NULL },
    { 0xF3, Mnemonic_repz, NULL, NULL },
    { 0xF4, Mnemonic_hlt, NULL, NULL },
    { 0xF5, Mnemonic_cmc, NULL, NULL },
    { 0xF6, Mnemonic_grp3a, "Eb", NULL },
    { 0xF7, Mnemonic_grp3b, "Ev", NULL },
    { 0xF8, Mnemonic_clc, NULL, NULL },
    { 0xF9, Mnemonic_stc, NULL, NULL },
    { 0xFA, Mnemonic_cli, NULL, NULL },
    { 0xFB, Mnemonic_sti, NULL, NULL },
    { 0xFC, Mnemonic_cld, NULL, NULL},
    { 0xFD, Mnemonic_std, NULL, NULL },
    { 0xFE, Mnemonic_grp4, "Eb", NULL },
    { 0xFF, Mnemonic_grp5, "Ev", NULL },
};

#endif